### ISSUE TITLE
icicle-kit build error

### ISSUE THREAD

**Issue by Jpgig** [linux4microchip/buildroot-external-microchip#1]
I am trying to build a Linux image for icicle-kit and getting the build error below:
![image](https://user-images.githubusercontent.com/115164852/206807082-68a9efbf-8632-4bab-93d1-7ade132e5234.png)

Any help is appreciated.

Thanks

**Comment by ConchuOD** [comment]
Hey @Jpgig could you try installing the "libssl-dev" package?

**Comment by ConchuOD** [comment]
> Hey @Jpgig could you try installing the "libssl-dev" package?

Alternatively, if you are on a version of Ubuntu that is newer than that listed in the readme, try installing "libssl1.1"

**Comment by Jpgig** [comment]
I have libssl-dev installed and its version is 3.0.2 as shown in the below image.

![image](https://user-images.githubusercontent.com/115164852/207429123-14065475-15a2-49ec-ae4b-0f1558758fee.png)

I'm using Ubuntu 22.04LTS version.

**Comment by ConchuOD** [comment]
> I have libssl-dev installed and its version is 3.0.2 as shown in the below image.
> 
> ![image](https://user-images.githubusercontent.com/115164852/207429123-14065475-15a2-49ec-ae4b-0f1558758fee.png)
> 
> I'm using Ubuntu 22.04LTS version.

I see. We validated against the version in the readme. Perhaps try manually installing libssl1.1:

https://askubuntu.com/a/1403961

**Comment by ConchuOD** [comment]
Gonna close this since it looks an incompatibility between the instructions in the readme that are for a specific version of Ubuntu & a later release.
