### ISSUE TITLE
The file I make in rootfs disappear after reboot

### ISSUE THREAD

**Issue by XianluoCat** [linux4microchip/buildroot-external-microchip#16]
I use the cmd make icicle_rootfs_defconfig to get the image and download it in emmc，use the cmd usbdmsc in HSS，I can see three partition in emmc. 
When I make a new file in rootfs，such as /opt/cat.c, when i reboot the kernel, the /opt become empty, the other file also the same.
Maybe the filesystem is readonly, how can i change it? 
Maybe i should mount the other storage to store the data? but i can't edit /etc/fstab to auto mount, because the file will also become to original one after reboot. （if i mount the third partition, the file i make in it while not change after reboot）
![Snipaste_2024-01-15_17-15-00](https://github.com/linux4microchip/buildroot-external-microchip/assets/44267941/15a31792-a13d-48f6-8fbd-f791bd148a7d)
![Snipaste_2024-01-15_17-19-40](https://github.com/linux4microchip/buildroot-external-microchip/assets/44267941/513f78fd-1ca5-45b8-9d75-3c6f05d1ef22)

**Comment by jamiegibbons** [comment]
Hi @XianluoCat,

If you want to add a file to your root filesystem you can do so by adding such to `board/microchip/icicle/rootfs-overlay/` and rebuilding your image. For example, to add a file as above, you can create `cat.c` and save it in `board/microchip/icicle/rootfs-overlay/opt/`. Then you can follow the steps to transfer your image to your mmc again.
However, as well as this method, with the resulting icicle_rootfs_defconfig image, if you create a file at runtime and reboot, it should also still have your file as this is designed (and tested) to be persistent. The same applies when using this image and adding a file to the root filesystem when the file system is mounted to your PC. 

Hope you find this helpful.

**Comment by XianluoCat** [comment]
I have tried to make icicle_rootfs_defconfig, but it has nothing changed, but when i make clean the project and do this again, it works. Thank you very much!
And I can find only one file in board/microchip/icicle/rootfs-overlay/, how can i edit /opt? should i add the /opt in it?
![image](https://github.com/linux4microchip/buildroot-external-microchip/assets/44267941/d977c189-3b6a-439c-99da-538d666f7739)
![image](https://github.com/linux4microchip/buildroot-external-microchip/assets/44267941/4dbc5f5d-707a-49ed-b167-cd6d1a43f1b6)

**Comment by jamiegibbons** [comment]
You can just create that directory in the rootfs-overlay directory and add whatever files you like. e.g. `cd buuildroot-external-microchip/board/microchip/icicle/rootfs-overlay/` and then `mkdir opt`. As mentioned, you can also do this at runtime with the rootfs image or with the file system mounted to your host machine.
