### ISSUE TITLE
Buildroot Image boots but no login prompt.

### ISSUE THREAD

**Issue by dourand** [linux4microchip/buildroot-external-microchip#17]
Hello. 

I am trying to build an Buildroot image for Icicle kit which will contain some application. 
First of all when I crosscompile all the packages I get the error "Disk Full"
The image gets succesfully built when changing boot.vfat size, but by doing this the board considers this an Invalid OS. 
![image](https://github.com/linux4microchip/buildroot-external-microchip/assets/43045582/41fe0a14-d984-434e-abe2-94beba231741)
When not building all of the packages, the image is built successfully. I burned it with dd to an SD card and it boots nominally. 
The issue now is that there is no login prompt. TTY is configured with getty 

![image](https://github.com/linux4microchip/buildroot-external-microchip/assets/43045582/1b2e9642-585e-4b19-98ec-26d024e4ce11)

Is there any suggestion?

**Comment by yanma** [comment]
I encountered a similar case with my PolarFire SoC Icicle Kit. Below is the method to reproduce the problem:

### PASS case (Linux boots up successfully)

Build an `sdcard.img` by the nominal procedure described in the [README.md:](https://github.com/linux4microchip/buildroot-external-microchip/blob/master/README.md)

```bash
git clone https://github.com/linux4microchip/buildroot-external-microchip.git -b 2023.02-mchp
git clone https://git.busybox.net/buildroot -b 2023.02.5
cd buildroot
BR2_EXTERNAL=../buildroot-external-microchip/ make icicle_defconfig
make
```

Burn the `sdcard.img` to an SD card and boot the image on the kit.

### FAIL case (Linux hangs during the boot process)

```bash
git clone https://github.com/linux4microchip/buildroot-external-microchip.git -b 2023.02-mchp
git clone https://git.busybox.net/buildroot -b 2023.02.5
cd buildroot
BR2_EXTERNAL=../buildroot-external-microchip/ make icicle_defconfig
make menuconfig
# Add vim: Target packages -> Text editors and viewers -> vim
make
```

Burn the `sdcard.img` to an SD card and boot the image on the kit.

Indeed, the sole difference between the PASS and FAIL cases is the addition of an extra package. Comparing the boot logs, the following error message appears only in the FAIL case:

```
Failed to add a System RAM resource at 80200000
```

I used MPFS-ICICLE-KIT-ES and its Reference Design Release v2023.06:
- https://github.com/polarfire-soc/icicle-kit-reference-design/releases/tag/v2023.06

I hope this information helps in identifying the root cause.

### Appendix

Followings are the boot logs corresponding to the PASS/FAIL case respectively.
- [PASS_case.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/14194269/PASS_case.txt)
- [FAIL_case.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/14194273/FAIL_case.txt)

**Comment by dourand** [comment]
I will check it out and come back to you. Will have access to the board on Tuesday.

How much time does the boot last? I left for quite some time, but still considering if I terminate it too soon.

Also I wasn't sure if there is any conflict caused by the pro-existing image in the eMMC. 
Right now I didn'r remove it and chose to boot it from the SD card.

**Comment by yanma** [comment]
In the pass case, the next line of the `printk: bootconsole [ns16550a0] disabled.` appears soon (less than 1sec).

I also tried flashing an image to the eMMC with the SD removed, but the result was the same. That is, it boots normally without adding any packages, but hangs at the line `bootconsole disabled` when adding vim.

By the way, upon reviewing my log, I noticed something odd in the `PASS_case.txt` as well. After the `bootconsole disabled` line, the timestamp rolls back to 0.000000, and the line `Linux version 6.1.74-linux4microchip` starts again. This may suggest that something went wrong at the `bootconsole disabled` line in the `PASS_case.txt` too, causing Linux to reboot, and the subsequent boot happened to succeed by chance.

I'm interested in whether you can reproduce the same phenomenon.

**Comment by ConchuOD** [comment]
> By the way, upon reviewing my log, I noticed something odd in the `PASS_case.txt` as well. After the `bootconsole disabled` line, the timestamp rolls back to 0.000000, and the line `Linux version 6.1.74-linux4microchip` starts again. This may suggest that something went wrong at the `bootconsole disabled` line in the `PASS_case.txt` too, causing Linux to reboot, and the subsequent boot happened to succeed by chance.

Just to note, this is normal behaviour when you have the sbi-based earlycon enabled.
Linux will print to the earlycon as it boots, and then will re-print all of the logs to the "real" console (tty0) once the driver for it has been loaded.

**Comment by ConchuOD** [comment]
> ```
> Failed to add a System RAM resource at 80200000
> ```

Thanks for the report, this does indeed look suspicious as that is where the kernel is loaded. I'll try to reproduce this locally.

**Comment by yanma** [comment]
> Just to note, this is normal behaviour when you have the sbi-based earlycon enabled.

Thank you for the information. I checked my configuration but `SERIAL_EARLYCON_RISCV_SBI` was disabled by default. I experimentally enabled it (it also required to enable `RISCV_SBI_V01`) but the situation did not change.

**Comment by ConchuOD** [comment]
> > Just to note, this is normal behaviour when you have the sbi-based earlycon enabled.
> 
> Thank you for the information. I checked my configuration but `SERIAL_EARLYCON_RISCV_SBI` was disabled by default. I experimentally enabled it (it also required to enable `RISCV_SBI_V01`) but the situation did not change.

Looking again, it seems to not have used the SBI earlycon, but rather the ns16550a directly.
Either way, makes little difference, it's earlycon behaviour and the exact earlycon driver used doesn't matter.

The underlying problem here is likely due to adding the package increasing the size of the initramfs causing it not to fit into the memory region we load the kernel+initramfs image to. Recently the images were converted to use systemd instead of busybox which increased their size, and adding vim might be the straw that broke the camels back.

**Comment by dourand** [comment]
So I restarted the whole process.

First using the icicle defconfig without any modification. Here is the logs when booting:

[Boot_defconfig.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/14237497/Boot_defconfig.txt)
[HSS_defconfig.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/14237498/HSS_defconfig.txt)

It still hangs at the same point. It has the same outputs as your PASSED one till that point. Waited around ~20 minutes to see if it will restart. I noticed that we have a different version of OpenSBI. Did you update anything on the board using Libero or SoftConsole? I just burnt the SD card.
The board that i use is a 2022 one. Could that be the problem? I used the 2023 configurations.

**Comment by ConchuOD** [comment]
> The board that i use is a 2022 one. Could that be the problem? I used the 2023 configurations.

I don't think that is the issue. As I mentioned the other day, I think that the image is just too big to fit and be relocated properly in the small cached ddr region allocated for the kernel at 0x8000_0000. Without the Vim package it doesn't hit that threshold. All of the images grew a lot recently because we switched from busybox to systemd, which is fine when the filesystem is not an initramfs but isn't leaving enough space to add any packages when it is.

We'll revert back to busybox for initramfs in the next day or two and hopefully that works better for yous.

**Comment by dourand** [comment]
> > The board that i use is a 2022 one. Could that be the problem? I used the 2023 configurations.
> 
> I don't think that is the issue. As I mentioned the other day, I think that the image is just too big to fit and be relocated properly in the small cached ddr region allocated for the kernel at 0x8000_0000. Without the Vim package it doesn't hit that threshold. All of the images grew a lot recently because we switched from busybox to systemd, which is fine when the filesystem is not an initramfs but isn't leaving enough space to add any packages when it is.
> 
> We'll revert back to busybox for initramfs in the next day or two and hopefully that works better for yous.

Yes i noticed the answer. I tried this without any modification. (No vim or some addtional package)

Ok, I ll check it out once it 'll be available.

**Comment by yanma** [comment]
> The underlying problem here is likely due to adding the package increasing the size of the initramfs causing it not to fit into the memory region we load the kernel+initramfs image to. Recently the images were converted to use systemd instead of busybox which increased their size, and adding vim might be the straw that broke the camels back.


Thank you for providing the information. I have a few questions.

- I think `initramfs` is used to provide the drivers and scripts which are necessary before the root file system is mounted. If so, why would user space applications like vim increase the size of `initramfs`?

- Looking at `output/build/linux-custom/arch/riscv/boot/dts/microchip/mpfs-icicle-kit.dts`, it states as below.
  ```
  kernel: memory@80000000 {
          device_type = "memory";
          reg = <0x0 0x80000000 0x0 0x4000000>;
  };
  ```
  It allocates only 64MB area while icicle kit has 2GB LPDDR. Can expanding the size for kernel solve the problem?

- I guess reverting from `systemd` to `busybox` is a temporary measure, and you're going to switch back to `systemd`. Is my understanding correct?

**Comment by ConchuOD** [comment]
Sorry for the delay, I've been off sick unfortunately.

> Thank you for providing the information. I have a few questions.
> 
> * I think `initramfs` is used to provide the drivers and scripts which are necessary before the root file system is mounted. If so, why would user space applications like vim increase the size of `initramfs`?

For the image in question, it is creating the initramfs, so when you add a package, it is added to the initramfs. This makes me wonder however, do you actually want to use an initramfs, or would a rootfs image be more suitable for you? We do have a rootfs configuration and will likely make it the default going forwards.

> * Looking at `output/build/linux-custom/arch/riscv/boot/dts/microchip/mpfs-icicle-kit.dts`, it states as below.
>   ```
>   kernel: memory@80000000 {
>           device_type = "memory";
>           reg = <0x0 0x80000000 0x0 0x4000000>;
>   };
>   ```  
>   It allocates only 64MB area while icicle kit has 2GB LPDDR. Can expanding the size for kernel solve the problem?

Yes and no. The rest of the 2 GiB is used for other regions. Increasing the size of this region will decrease the size of other regions with different purposes.
When Linux has fully booted it will make use of the whole region, it is just very early on in boot that this 64 MiB restriction applies.

> * I guess reverting from `systemd` to `busybox` is a temporary measure, and you're going to switch back to `systemd`. Is my understanding correct?

Hopefully, yes, but this may not be possible for the initramfs image.

**Comment by yanma** [comment]
Sorry for the delay and thank you for your comment.

> would a rootfs image be more suitable for you?

Yes, I also think so.

> We do have a rootfs configuration and will likely make it the default going forwards.

Do you support rootfs configuration with buildroot? My colleague googled about this issue and found the article below (I'm not sure this is also applicable to the buildroot-external-microchip).

> Well, actually, the initramfs created by Buildroot is not really suitable as a first stage filesystem, it is really intended for an initramfs-only setup.

https://lore.kernel.org/all/20180610071552.ym7c6xb4j3aa6vlh@sapphire.tkos.co.il/T/

On the other hand, I found the yocto project explicitly supports both RootFS and Initramfs.
https://github.com/polarfire-soc/meta-polarfire-soc-yocto-bsp?tab=readme-ov-file#building-board-disk-image

Considering above, I may switch to yocto.

> Yes and no. The rest of the 2 GiB is used for other regions. Increasing the size of this region will decrease the size of other regions with different purposes. When Linux has fully booted it will make use of the whole region, it is just very early on in boot that this 64 MiB restriction applies.

I roughly understood but how did you decide the usage of the regions? There are several memory regions defined in `mpfs-icicle-kit.dts` but I could not find corresponding document to explain the design.
https://github.com/linux4microchip/linux/blob/linux-6.1-mchp/arch/riscv/boot/dts/microchip/mpfs-icicle-kit.dts

> Hopefully, yes, but this may not be possible for the initramfs image.

I understood.

Anyway, now it became clear why this boot failure happens. Thank you for your support.
