### ISSUE TITLE
printk: bootconsole [ns16550a0] disabled

### ISSUE THREAD

**Issue by XianluoCat** [linux4microchip/buildroot-external-microchip#19]
I use BR2_EXTERNAL=../buildroot-external-microchip/ make icicle_rootfs_defconfig to build, but the kernel log end with printk: bootconsole [ns16550a0] disabled.
here is the kernel log:
[startlog.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/14384819/startlog.txt)
here is defconfig:
[buildroot_defconfig.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/14384821/buildroot_defconfig.txt)
here is .config in output/build/linux-custom:
[linux-costum-config.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/14384827/linux-costum-config.txt)
I find the output/image/mpfs_icicle.itb is smaller than before(about 30MB).
![Snipaste_2024-02-23_19-37-03](https://github.com/linux4microchip/buildroot-external-microchip/assets/44267941/0e20024e-882b-405a-9d0b-c88ec2ccaa54)
Any help will be appreciate.

**Comment by XianluoCat** [comment]
The above startlog is on our board, we use the same sdcard.img both in myboard and evaluate board, here are the logs.
ourboard:
[myboard.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/14392051/myboard.txt)
icicle kit board:
[evboard.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/14392052/evboard.txt)
It work well in icicle kit board but stop at printk: bootconsole in myboard.
What's more, I find  in myboard, "printk: bootconsole [ns16550a0] disabled" display only once and stop, but in evboard it display twice and go on.

**Comment by xiaogu-arch** [comment]
Hello, I have also encountered a similar problem. How did you solve it in the end?
