### ISSUE TITLE
Download the sdcard.img to the board, the kernel can't start, the eMMC partition is also a little wrong.

### ISSUE THREAD

**Issue by XianluoCat** [linux4microchip/buildroot-external-microchip#2]
The reason is i want to add the can module to the kernel, so i make linux-menuconfig and make to build the image. 
The sdcard.img file is about 147.1MB, after i use the dd command downland it to the board, i find the kernel can't start, and there seems is no root filesystem in the eMMC. Hope anyone can help me, thanks.
![image](https://user-images.githubusercontent.com/44267941/212443119-a8e54809-7a1b-47c0-be64-7b148727dc48.png)
![image](https://user-images.githubusercontent.com/44267941/212443065-036c7933-63ff-4750-be1d-929f12c4cb98.png)
I had download the yocto reference image to the board, it run ok, its partition is here.
![image](https://user-images.githubusercontent.com/44267941/212443363-e08c19f3-96fa-401c-a44d-3cb5b1f620af.png)
So i think something must be wrong.

**Comment by hughbreslin** [comment]
Hi @XianluoCat have you tried flashing a standard BR External image without the menuconfig change to see if the standard image builds?

**Comment by XianluoCat** [comment]
yes, I have tried to use the defconfig, it can start, but finally end kernel panic, here is the log.
I get file in reference image to replace the rootfs/bin/busybox, it also doesn't work。
[kernel panic.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/13110548/kernel.panic.txt)

**Comment by XianluoCat** [comment]
@hughbreslin ，any proceed please tell me.

**Comment by jamiegibbons** [comment]
Hi @XianluoCat, I wonder if you may be force unmounting the mmc by pressing ctrl + C in the HSS console once the dd transfer terminal returns, this can cause kernel panic as the full image has not been transferred and is therefore corrupt. In most cases the image needs longer then this return signal to complete the transfer. Waiting 10-20 seconds after the dd command returns will usually ensure that the transfer is complete. The bytes read on the HSS console for the mmc should be >= to the transfer size from your dd command before you hit ctrl + C. 
The default icicle_defconfig provided with the [linux4microchip 2023.09 release](https://github.com/linux4microchip/buildroot-external-microchip/releases/tag/linux4microchip%2Bfpga-2023.09) has been tested with the [2023.06 reference design release](https://github.com/polarfire-soc/icicle-kit-reference-design/releases/tag/v2023.06). Please ensure this matches the resources you have, ensure there are no build errors, and retry with the above suggestion. Please follow [our guide](https://github.com/linux4microchip/buildroot-external-microchip/tree/linux4microchip%2Bfpga-2023.09#create-an-image-for-emmcsd-card) if you have any problems with this step.

**Comment by XianluoCat** [comment]
hello @jamiegibbons ，as your advice, I changed the newest linux4microchip and hss, and wait for the transmit. the panic really disappear, but the new problem occur:
1. the shell need me to login with passwd, but i did not set the passwd in buildroot system configurature, then i set the passwd and the file ".config" can find what i set :BR2_TARGET_ENABLE_ROOT_LOGIN=y  BR2_TARGET_GENERIC_ROOT_PASSWD="123456", but if i login with these "root  123456", it also does not work, finally i find the answe to change routput/target/etc/shadow "root:xxxx" to "root::0:::::: ", then i login it work. it is a bug in the buildroot ?
2. The log remind me i need the libatomic.so.1, I find the same name in /output/build/host-gcc-final-11.3.0/build/riscv64-buildroot-linux-gnu/libatomic/.libs/libatomic.so.1, then i copy it to ROOTFS/usr/lib, but the log does not change, i also cannot use the shell cmd like 'ls' etc. , here is the log. 
[requiresharelib.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/13255674/requiresharelib.txt)

**Comment by jamiegibbons** [comment]
Hi @XianluoCat, I am happy to hear the original issues have been sorted. 

With our default configurations provided, the login user is "root" with no password. This has been tested with the 2023.09 release and will log you in. If you would like to set a password or any other login options, you can do so with one of the following two methods. When setting kconfig options you can add them to the original defconfig file - if you know what you are doing - and then rerun the following commands: `BR2_EXTERNAL=../buildroot-external-microchip/ make icicle_defconfig` and `make`. For less experienced users, however, I would recommend using your favourite configuration tool - I use menuconfig, with the command `make menuconfig`. Using this tool you can search for the configuration you are looking for with `/`. When you set a kconfig using this tool it will ensure that all of the dependencies for this option are also set correctly. 
However, with our default "icicle_defconfig", `BR2_TARGET_ENABLE_ROOT_LOGIN` is set by default. If you set `BR2_TARGET_GENERIC_ROOT_PASSWD` to "123456" using menuconfig, it should work for you, logging in with the user "root" and the password "123456". I have tested this with our "linux4microchip+fpga-2023.09" source this morning.
I have tested both the default login (root, with no password) and the login you attempted (root, with password 123456) this morning with our 2023.09 release. Both logins work with no libatomic/rootfs errors and I can use shell commands including "ls". `ls /` will show you the filesystem. 
Have you altered anything else? I am assuming you are using default HSS (2023.09), icicle kit reference design (2023.06), buildroot (2022.02) and buildroot-external-microchip (linux4microchip+fpga-2023.09)?

**Comment by XianluoCat** [comment]
Thanks your answer. This is my env: The MPFS_ICICLE_BASE_DESIGN_2023_06 (there is the .job file, I use flashpro Express to program it, I have tried to download core-image-minimal-dev-icicle-kit-es-20230928081155.rootfs.wic.gz in it, and it run well). buildroot (2022.02) and buildroot-external-microchip (linux4microchip+fpga-2023.09). Here is all the log I can provide, may be you can find some wrong operate in it. 
buildlog: if I don't use sudo cmd, there will some error occur, but buidroot README said it doesn't need sudo cmd. 
downloadimagelog: it download so fast, may be some error in it.
kernellog: the passwd disapper, I don't know why. 
[buildimagelog.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/13291532/buildimagelog.txt)
[downloadimagelog.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/13291567/downloadimagelog.txt)
[HSSstartdownloadlog.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/13291534/HSSstartdownloadlog.txt)
[kernellog (1).txt](https://github.com/linux4microchip/buildroot-external-microchip/files/13291535/kernellog.1.txt)

**Comment by jamiegibbons** [comment]
I have checked the logs you provided. I do not see anything wrong with the download image log and the HSS start download log, as the bytes received is larger than the bytes transferred by the dd command. If you would like to see the progress of the transfer you can add `status=progress` to your `dd` command.
Unfortunately, the kernel log you provided is empty (0 bytes) so I could not get any information from this. Could you try uploading the kernel log again?
With regards the build image log, you should not use `sudo` when using `make`, this will corrupt the file permissions ([more information](https://unix.stackexchange.com/a/20956)).
Could you also upload your config file so I can take a look at that and hopefully be able to advise further. You can do this by using the `make savedefconfig BR2_DEFCONFIG=<path+name-you-want-to-save-your-file-to>` and then uploading this file, e.g. `make savedefconfig BR2_DEFCONFIG=/home/why/PolarFire/test_defconfig`. At the moment, I would suggest fixing your make error as you should not be using `sudo make`. Are you running your build in a docker container?

**Comment by XianluoCat** [comment]
I am sorry for the empty file, here is the kernel log with default set and the defconfig file. 
I just build it in Ubuntu 20.04 LTS, do not use any thing else.
[test_defconfig.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/13302711/test_defconfig.txt)
[kernellog_nopasswd.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/13302716/kernellog_nopasswd.txt)

**Comment by XianluoCat** [comment]
@jamiegibbons I just remember that when i first build the project, there is an error occur, but i can not remember the detail, the log said error when make the testcode with i586 compiler, so i download the riscv compiler, and use it to change the i586 in a .cmake file, but there is a fortrans line i did not change.

**Comment by XianluoCat** [comment]
I rebuild the buildroot in new PC with your advice, eventhough I still use the sudo cmd to start build, but it finally running well, and not any error occur, I am sure the operation is the same. 
The only different between the two PC is the net connection and vmware workstation version, in version 17 pro not work, but in version 16 pro can work. 
I will close the commet, thanks any way.
