### ISSUE TITLE
glibc for v2024.02

### ISSUE THREAD

**Issue by ikazinov** [linux4microchip/buildroot-external-microchip#20]
Hi,

Previously I used v2023.2:
...
git clone https://github.com/linux4microchip/buildroot-external-microchip.git -b linux4microchip+fpga-2023.02
git clone https://git.busybox.net/buildroot -b 2023.02
...
In this version I have glibc option (make menuconfig > Toolchain)
![image](https://github.com/linux4microchip/buildroot-external-microchip/assets/22839381/d4912caa-9b51-43fa-8df2-97cc6b59a288)

I've tried to switch to new v2024.02:
...
git clone https://github.com/linux4microchip/buildroot-external-microchip.git -b linux4microchip+fpga-2024.02
git clone https://git.busybox.net/buildroot -b 2024.02
...
and after 'make menuconfig' I've got only 2 options
![image](https://github.com/linux4microchip/buildroot-external-microchip/assets/22839381/f4a45ae5-4a5a-46a3-a226-4fc36dfc9432)

So, could anyone help me to get glibc in v2024.02 ?
Thank you in advance.

**Comment by jamiegibbons** [comment]
Hi @ikazinov, we currently do not support Buildroot v2024.02. For our latest release: linux4microchip+fpga-2024.02, please use Buildroot v2023.02.5 as stated in [our docs](https://github.com/linux4microchip/buildroot-external-microchip/tree/linux4microchip%2Bfpga-2024.02?tab=readme-ov-file#build), i.e. `git clone https://git.busybox.net/buildroot -b 2023.02.5`

However, with a change in Buildroot version from 2023.02 to 2024.02 you should still be able to see the glibc toolchain option provided if that is all you have changed, i.e. you have not changed your config. If you have made some changes, I would advise checking such changes don't effect the below options.

![image](https://github.com/linux4microchip/buildroot-external-microchip/assets/106663987/ab0eeda4-d302-4ecf-ae19-930e773a6b99)

**Comment by ikazinov** [comment]
Hi [jamiegibbons](https://github.com/jamiegibbons),
I've tried:
...
git clone https://github.com/linux4microchip/buildroot-external-microchip.git -b linux4microchip+fpga-2024.02
git clone https://git.busybox.net/buildroot -b 2023.02.5
BR2_EXTERNAL=../buildroot-external-microchip/ make icicle_defconfig
make
...
and it works fine, glibc is default option.
Thank you.
