### ISSUE TITLE
perf kernel support.

### ISSUE THREAD

**Issue by mdpcardoso** [linux4microchip/buildroot-external-microchip#3]
First of all thank you for providing support for Buildroot, which is a great achievement. I've been using it for the last few months.

I've tried to enable the `perf` Buildroot package (and it compiles), and verified the kernel option was enabled, but the kernel refuses to boot (no message after `Starting kernel ...`). I've also tried to compile the kernel alone with just `CONFIG_PERF_EVENTS`, but it also refuses to boot even without building it using the Buildroot system.

```
OpenSBI v1.0
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

Platform Name             : Microchip PolarFire(R) SoC
Platform Features         : medeleg
Platform HART Count       : 5
Platform IPI Device       : aclint-mswi
Platform Timer Device     : aclint-mtimer @ 1000000Hz
Platform Console Device   : mmuart
Platform HSM Device       : mpfs_hsm
Platform Reboot Device    : mpfs_reset
Platform Shutdown Device  : mpfs_reset
Firmware Base             : 0xa000000
Firmware Size             : 142 KB
Runtime SBI Version       : 0.3

Domain0 Name              : root
Domain0 Boot HART         : 1
Domain0 HARTs             : 1,2,3,4
Domain0 Region00          : 0x0000000002008000-0x000000000200bfff (I)
Domain0 Region01          : 0x0000000002000000-0x0000000002007fff (I)
Domain0 Region02          : 0x000000000a000000-0x000000000a03ffff ()
Domain0 Region03          : 0x0000000000000000-0xffffffffffffffff (R,W,X)
Domain0 Next Address      : 0x0000001000200000
Domain0 Next Arg1         : 0x0000000000000000
Domain0 Next Mode         : S-mode
Domain0 SysReset          : yes

Domain1 Name              : src.bin
Domain1 Boot HART         : 1
Domain1 HARTs             : 1*,2*,3*,4*
Domain1 Region00          : 0x000000000a000000-0x000000000a03ffff ()
Domain1 Region01          : 0x0000000000000000-0xffffffffffffffff (R,W,X)
Domain1 Next Address      : 0x0000001000200000
Domain1 Next Arg1         : 0x0000000000000000
Domain1 Next Mode         : S-mode
Domain1 SysReset          : yes

Boot HART ID              : 1
Boot HART Domain          : src.bin
Boot HART ISA             : rv64imafdcsu
Boot HART Features        : scounteren,mcounteren
Boot HART PMP Count       : 16
Boot HART PMP Granularity : 4
Boot HART PMP Address Bits: 36
Boot HART MHPM Count      : 2
Boot HART MIDELEG         : 0x0000000000000222
Boot HART MEDELEG         : 0x000000000000b109


U-Boot 2022.01 (Feb 14 2023 - 15:55:51 +0000)

CPU:   rv64imafdc
Model: Microchip PolarFire-SoC Icicle Kit
DRAM:  1.8 GiB
MMC:   mmc@20008000: 0
Loading Environment from nowhere... OK
In:    serial@20100000
Out:   serial@20100000
Err:   serial@20100000
Net:   eth0: ethernet@20112000
Hit any key to stop autoboot:  0 
Trying to boot from QSPI...
Could not find a valid device for spi-nand0
List of MTD devices:
No MTD device found
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:2...
Found U-Boot script /boot.scr
574 bytes read in 10 ms (55.7 KiB/s)
## Executing script at 1008100000
5721548 bytes read in 263 ms (20.7 MiB/s)
## Loading kernel from FIT Image at 1008100000 ...
   Using 'kernel_dtb' configuration
   Trying 'kernel' kernel subimage
     Description:  Linux kernel
     Type:         Kernel Image
     Compression:  gzip compressed
     Data Start:   0x10081000cc
     Data Size:    5696860 Bytes = 5.4 MiB
     Architecture: RISC-V
     OS:           Linux
     Load Address: 0x1000200000
     Entry Point:  0x1000200000
     Hash algo:    sha256
     Hash value:   2b59a1f3d00dccab6f36069962bb36ea588bdb40283276471c8622426d92b827
   Verifying Hash Integrity ... sha256+ OK
## Loading fdt from FIT Image at 1008100000 ...
   Using 'kernel_dtb' configuration
   Trying 'base_fdt' fdt subimage
     Description:  Flattened Device Tree blob
     Type:         Flat Device Tree
     Compression:  uncompressed
     Data Start:   0x100866ef38
     Data Size:    20155 Bytes = 19.7 KiB
     Architecture: RISC-V
     Load Address: 0x1040000000
     Hash algo:    sha256
     Hash value:   72e930d1e1d594c0e502a4280a720af008a675e9a136149d3c3548772380259a
   Verifying Hash Integrity ... sha256+ OK
   Loading fdt from 0x100866ef38 to 0x1040000000
   Booting using the fdt blob at 0x1040000000
   Uncompressing Kernel Image
   Loading Device Tree to 000000100fff8000, end 000000100ffffeba ... OK

Starting kernel ...
```

Is it an expected behavior or are the performance counters not supported?

**Comment by ConchuOD** [comment]
Hey @mdpcardoso I would not have expected enabling CONFIG_PERF_EVENTS to make the system unbootable.
I'll take a look at this tomorrow and get back to you then hopefully.

**Comment by ConchuOD** [comment]
> Hey @mdpcardoso I would not have expected enabling CONFIG_PERF_EVENTS to make the system unbootable. I'll take a look at this tomorrow and get back to you then hopefully.

Hmm, I tried this today, albeit with the latest linux4microchip+fpga-2023.02 tag.
I opted not to build perf support into my userspace as you were able to reproduce this issue with just the kernel option enabled.
I was able to boot successfully with that combination, so I am not sure what may have gone wrong for you.

The only thing that I can think of is that you did the build while we were in the processes of pushing the repositories for the linux4microchip+fpga-2023.02 & ended up with mixed versions of things.

I would suggest updating to the [v2023.02 Icicle Kit Reference Design Release](https://github.com/polarfire-soc/icicle-kit-reference-design/releases/tag/v2023.02) & the linux4microchip+fpga-2023.02 tag of buildroot-external and trying again?

The other option is leaving your FPGA bitstream as-is & trying out linux4microchip+fpga-2022.11 of buildroot-external instead.

Silly question maybe, but does it boot again if you just remove PERF_EVENTS from your kernel config?

**Comment by ConchuOD** [comment]
@mdpcardoso Hey! Wondering if I can close this issue since I could not reproduce it, or if you perhaps have some response to my comment on 28/02.

**Comment by mdpcardoso** [comment]
Hello @ConchuOD , thanks for your reply and sorry for taking so long, some stuff got in the way.

I am able to confirm that the tag linux4microchip+fpga-2023.02 and the matching Reference Design do fix the issue. Just for reference, I was facing the issue on an old commit / release from November 2022 (can't recall which one right now).

Thanks again, I think we can now close the issue.
