### ISSUE TITLE
`wchar`, `NPTL` and `PCRE` support

### ISSUE THREAD

**Issue by keck-in-space** [linux4microchip/buildroot-external-microchip#4]
Hello,

I am attempting to integrate [Aravis](https://github.com/AravisProject/aravis) into the PolarFire SOC buildroot build by following the steps outlined in this Buildroot mailing list [post](https://lore.kernel.org/buildroot/ea-mime-61d5bfe1-7547-225ebd37@www-7.net-c.com/)

This is the Config.in file that is in the post

```
+config BR2_PACKAGE_ARAVIS
+    bool "aravis - GigE Camera"
+    depends on BR2_USE_WCHAR
+    depends on BR2_TOOLCHAIN_HAS_THREADS_NPTL
+    depends on BR2_PACKAGE_PCRE_16
+    depends on BR2_PACKAGE_PCRE_32
+    select BR2_PACKAGE_LIBGLIB2
+    select BR2_PACKAGE_LIBXML2
+    help
+      aravis provides the support of GigE camera
+      and USB3Vision camera.
+      https://github.com/AravisProject/aravis
+
+comment "aravis needs a toolchain w/ wchar, NPTL, PCRE 16/32"
+    depends on !BR2_USE_WCHAR || !BR2_TOOLCHAIN_HAS_THREADS_NPTL || \
+    !BR2_PACKAGE_PCRE_16 || !BR2_PACKAGE_PCRE_32
```

However, when I try to select this using `make menuconfig`, I see the error that "aravis needs a toolchain w/ wchar, NPTL, PCRE 16/32", but I do not see an option to enable any of those in the Toolchain settings of the menu. Does the Polarfire support these options, or is this not possible using the PolarFire SOC at this time?

**Comment by ConchuOD** [comment]
> However, when I try to select this using `make menuconfig`, I see the error that "aravis needs a toolchain w/ wchar, NPTL, PCRE 16/32", but I do not see an option to enable any of those in the Toolchain settings of the menu.

Hmm, so for me if I do `BR2_EXTERNAL=../buildroot-external-microchip/ make icicle_defconfig menuconfig` I can see that my toolchain does in fact USE_WCHAR & HAS_THREADS_NPTL. These seem to not be user selectable options - and instead are set by the toolchains's detected version of libc.

The other two options, PCRE_16 & _32 can be found in the "Target packages" section.

```
  │     -> Target packages                                                                                                                                                                                                                                                            
  │       -> Libraries                                                                                                                                                                                                                                                                
  │         -> Text and terminal handling                                                                                                                                                                                                                                             
```
If you enable pcre, the options for 16-bit & 32-bit will become visible.

Usually in these sorts of circumstances, I use / & just search for the BR2_WHATEVER string, it often at least explains why the option isn't enabled.

Hope that is helpful.
