### ISSUE TITLE
misaligned-access reported by sanity checker 

### ISSUE THREAD

**Issue by gngram** [linux4microchip/buildroot-external-microchip#5]
**Linux Version:** 5.15.92-linux4microchip+fpga-2023.02 (On branch latest linux-5.15-mchp+fpga too)
**Step to reproduce:**
Enable following kernel configuration and respective security modules:
```
CONFIG_UBSAN y
CONFIG_UBSAN_BOUNDS y

```
Compile and load kernel,  too many misaligned-access reported by sanity checker.

Kernel boot log attached.
[kernel_crash_new.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/11540550/kernel_crash_new.txt)

**Comment by ConchuOD** [comment]
Hey @codehub8, I will look into this.

**Comment by gngram** [comment]
Hi, Any progress on this?

**Comment by ConchuOD** [comment]
> Hi, Any progress on this?

Took me longer than I would like to get to this, sorry about that.

It looks like there's nothing specific to our downstream kernel here - I can reproduce all of this with mainline Linux.
I think the main issue here is that you enabled CONFIG_UBSAN_ALIGNMENT, but on RISC-V misaligned accesses are permitted.
It gets enabled by default if you enable CONFIG_UBSAN, so needs to be specifically disabled.
I was able to reproduce a boot failure with mainline Linux & with our downstream 6.1 based vendor kernel, found that disabling CONFIG_UBSAN_ALIGNMENT allowed the system to boot once more.

**Comment by ConchuOD** [comment]
I'm going to close this, since there's been no response in a month & the issue appears to just be kernel misconfiguration.
