### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by n42603** [linux4microchip/buildroot-external-microchip#9]
Fails trying to access sources.buildroot.net/linux4microchip+fpga-2023.09.tar.gz

Gets a 404 error because apparently it does not exist.

**Comment by jamiegibbons** [comment]
Hello,

That error message would lead me to believe that you are having a network error as opposed to it being an issue with the source. When there is a network error while running a build, Buildroot tries to fallback on "sources.buildroot.net", however, it will not find what it is looking for there. Are you using a default example defconfig from our repository, e.g. icicle_defconfig? What step is it failing at during the build? 

This release tag has been tested and I am unable to reproduce this error. Can you check your network connection and try to build again? If you are still getting this error after checking this, could you let us know what your defconfig is and what build step it is failing at?

**Comment by n42603** [comment]
Hello Jaime,

There is an issue in that the script, after being redirected with a 302 error, and successfully connecting to codeload.github.com was unable to establish a SSL connection. That is when it attempted to access “sources.buildroot.net”. You say it will not find what it is looking for there, which is why the 404 error occurred, then why is it trying to access that repository?

I am using the default icicle_defconfig.

I will try to solve the SSL issue and try again.

David


From: Jamie Gibbons ***@***.***>
Sent: Wednesday, October 11, 2023 1:47 AM
To: linux4microchip/buildroot-external-microchip ***@***.***>
Cc: Barnett, David [US] (SP) (Contr) ***@***.***>; Author ***@***.***>
Subject: EXT :Re: [linux4microchip/buildroot-external-microchip] Fails to build (Issue #9)


Hello,

That error message would lead me to believe that you are having a network error as opposed to it being an issue with the source. When there is a network error while running a build, Buildroot tries to fallback on "sources.buildroot.net", however, it will not find what it is looking for there. Are you using a default example defconfig from our repository, e.g. icicle_defconfig? What step is it failing at during the build?

This release tag has been tested and I am unable to reproduce this error. Can you check your network connection and try to build again? If you are still getting this error after checking this, could you let us know what your defconfig is and what build step it is failing at?

**Comment by jamiegibbons** [comment]
Hi David,

Thank you for telling us what defconfig you are using, please let us know how it goes when you try again. As explained previously, when a network error has occurred and therefore the build cannot find what it is looking for, it tries to search for it in the Buildroot sources at "sources.buildroot.net" - something of a "failsafe" attempt -, as this is not where the source for our kernel or U-Boot is, it will be unsuccessful, hence the 404 not found error. It is likely there was an error previous to this that will tell us more about the real reason the build has failed.

As mentioned before, as we are unable to reproduce this error - since building from source while following this repository's readme does not return any error for us - it is very hard to help/advise further without more information. If the retry does not work could you please send us the relevant part of the build log so we can attempt to assist further.

**Comment by n42603** [comment]
Hi Jaime,

I really appreciate the quick response. As I previously mentioned, the error was failure to establish a SSL connection. Since I am not an internet expert, I have referred my error to those in my organization that may be able to help.

I think if this is corrected that I will be able to successfully build the repository.

Thanks for the help.

David

From: Jamie Gibbons ***@***.***>
Sent: Wednesday, October 11, 2023 7:15 AM
To: linux4microchip/buildroot-external-microchip ***@***.***>
Cc: Barnett, David [US] (SP) (Contr) ***@***.***>; Author ***@***.***>
Subject: EXT :Re: [linux4microchip/buildroot-external-microchip] Fails to build (Issue #9)


Hi David,

Thank you for telling us what defconfig you are using, please let us know how it goes when you try again. As explained previously, when a network error has occurred and therefore the build cannot find what it is looking for, it tries to search for it in the Buildroot sources at "sources.buildroot.net" - something of a "failsafe" attempt -, as this is not where the source for our kernel or U-Boot is, it will be unsuccessful, hence the 404 not found error. It is likely there was an error previous to this that will tell us more about the real reason the build has failed.

As mentioned before, as we are unable to reproduce this error - since building from source while following this repository's readme does not return any error for us - it is very hard to help/advise further without more information. If the retry does not work could you please send us the relevant part of the build log so we can attempt to assist further.
